package exception;

public class TryException {

	public TryException() {
		// TODO Auto-generated constructor stub
	}

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		int a = 34;
		int b = 21;
		
		try {
			
			int z = a + b;
			
			try {
				
				int p = z + 2;
				System.out.println(p);
				
			}catch(ArithmeticException ae) {
				
				System.out.println("First Exception" + ae);
			}
			
		}catch(ArithmeticException ae) {
			
			System.out.println("This is my Second Exception" + ae); 
		}
		

	}

}
